### ISSUE TITLE
Python 2.x support

### ISSUE THREAD

**Issue by ghost** [CamdenClark/pylichess#1]
Can you provide version of this wrapper for Python 2.5-2.6 ?

**Comment by CamdenClark** [comment]
I would only consider giving 2.7 support and even then I have too little
experience doing that. Any chance you could give it a try?

**Comment by ghost** [comment]
@CamdenClark, not try it yet, but very interested in developing simple desktop client.
Think, you know this:
https://github.com/NikolaiT/lichess_cheat
So, is it possible make this desktop lichess app?

**Comment by CamdenClark** [comment]
I have no interest in helping people cheat on lichess. Sorry.
